version: '3'
services:
  geth0:
    # change image back to stable when Geth v1.10.18 is released and [internal/ethapi: add refund to StructLogRes](https://github.com/ethereum/go-ethereum/commit/b5a129ea248f259a367d804cdf396ce442109d85) included.
    image: "ethereum/client-go:latest"
    container_name: zkevm-geth0
    ports:
      - 8545:8545
    command: --dev --vmdebug --gcmode=archive --http --http.addr 0.0.0.0 --http.port 8545 --http.vhosts "*" --http.corsdomain "*" --http.api "eth,net,web3,personal,txpool,miner,debug" --verbosity 6

